### ISSUE TITLE
[Proposal] Add http Request+Response getter/setter ?

### ISSUE THREAD

**Issue by samber** [samber/oops#4]
Providing HTTP requests and responses in logs make it very easy to debug an API (both client and server).

Is it necessary to add yet another series of getter+setter or should we use the `.With()` helper?

**Comment by antonsergeyev** [comment]
I'm interested in this, since we often write HTTP clients and have to debug them.
Though Go already provides helper functions such as `httputil.DumpRequestOut` and `httputil.DumpResponse`, there are a few caveats that I'd like to know your opinion about:
* Requests and responses may large bodies unresasonable for logging (such as files). Usually this can be detected and worked-around with help of `content-size`, but sometimes when the body is streamed, this header is omitted.
So I think we can't always automatically decide whether the body should be printed. What would you do in this case?
* Printing request/response body itself can lead to an error (see the signatures of DumpRequestOut and DumpResponse). In such cases, we probably want to just log an error in place of a body, though it can be confusing.

**Comment by samber** [comment]
That's cool, i didn't know about `httputil` helpers before.

I agree, I had similar issues with my loggers in the past. There is no perfect way decide whether the body is readable and not too large. 

Did you check in the Sentry library how they manage that?

2 solutions immediately come to my mind:
- split builder into 2 methods: `.Req(...)` + `.ReqWithBody()`
- add 2 getters, and the output functions (LogValuer, ToMap, Format, Marshal...) pick automatically the shortest

One more point: request and response bodies are Go readers and writers. Dumps should be done carefully!

**Comment by antonsergeyev** [comment]
Sentry [looks at content-length](https://github.com/getsentry/sentry-go/blob/eec094e9470dd3855eaf47b025d853bcbc13df68/scope.go#L104) and ignores requests over 10 kilobytes (maxRequestBodyBytes).

I was thinking of starting with something simple such as 
```
func (o OopsErrorBuilder) WithHttpRequest(req *http.Request, withBody bool) OopsErrorBuilder {
	reqDump, err := httputil.DumpRequestOut(req, withBody)
	if err != nil {
		reqDump = []byte(fmt.Sprintf("could not dump HTTP request: %v", err))
	}

	return o.With("http_request", string(reqDump))
}
```

So the user has to decide whether to dump the whole body.

We can also make it smarter / more complex, e.g. automatically shorten the body based on user-supplied limit. But I think a sane default behavior should be enough for most users.
